### ISSUE TITLE
Super ability

### ISSUE THREAD

**Issue by Jameywags** [lshadler/game-jam-july-2020#40]
Gain a use of super invincibility for every 10 or so notes you collect

**Comment by wtait1** [comment]
1. Should the invincibility activate immediately, or be keystroke-triggered?
2. How should the invincibility be communicated? Taking the Mario Star as an example there are both visual & audio cues (rainbow flashing + special music)
    - i.e. the music could become 🅱️ oosted
3. How long should it last?

**Comment by tboz221** [comment]
Another super Idea could be to blast away all "enemy objects" off-screen, leaving music notes behind.

**Comment by sumwatshade** [comment]
I like the idea of a random ability coming up. Random between:

- invincibility
- tomatoes disappear
- drums disappear
- gains some health back
- sax solo!
